### PR TITLE
Rewrite motor_driver module to shorten, format, and fix (handle) some edge cases

### PR DESCRIPTION
**Pull request by iansan5653**
This branch does verify successfully using the Arduino IDE, however I'm not 100% certain the left and right pins are correctly referenced because I'm not sure exactly how it's set up, so please test in the rover prior to merging.

### CODE REVIEW

**Comment by iansan5653** [comment]
This also updates the readme; meant to push those directly to master but I forgot.

**Comment by arnoldlperez** [comment]
Looks good as well but will test it before merging anyway. Also after playing around the motors, the PWM values don't correspond to a linear percentage anyway and since they are not calibrated the same, a similar PWM value doesn't result in a similar RPS for both motors so I might just simplify it further and scrap the percentage all together.

**Comment by iansan5653** [comment]
We should definitely try to calibrate those PWM values then. The easiest way would be to generate a calibration curve by mapping PWM input values to RPM output values; then we can easily get speed from the RPM and wheel radius and instead of setting PWM or %, set speed. 

To get RPM, we can use a tachometer. Want me to email my Mech Lab professor and see if I can borrow one?

**Comment by arnoldlperez** [comment]
Sounds good, I would check with Tom to see how much we need variable speed for our rover but we would need some sort of sensor like a tachometer or encoders if we do want it. At the moment the rover is using the driver motors essentially as digital on and off switch (but able to reverse) and using in between value may cause unexpected results.

**Comment by iansan5653** [comment]
I mean that we should make a static function that maps PWM values to speed values, which we can generate ahead of time. So we wouldn't need an onboard tachometer, unless we think the motor calibration will change over time. Either way we need some way to make the two motors behave the same so the rover can steer and go straight without turning.

**Comment by arnoldlperez** [comment]
Makes sense, the calibration will vary a bit based on terrain (and maybe slippage) but it should be good enough to allow it to turn and go straight at lower PWM values. I think at max PWM it does go straight, but I think we need to test it again with our final body. So yeah, we wouldn't need it on board but we would need a sensor to calibrate it and save it onto the rover.

**Pull request merged**
